sudo: required

language: cpp

services:
  - docker

cache:
  ccache: true

env:
  global:
    - CCACHE_DIR=${HOME}/.ccache
    - DOCKER_CONTAINER=px4io/px4-dev-ros2-ardent:2018-10-16
    - PX4_FIRMWARE=https://github.com/PX4/Firmware.git
    - BUILD="source /opt/ros/ardent/setup.sh; mkdir -p ~/colcon_ws/src; cd ~/colcon_ws; ln -s ${TRAVIS_BUILD_DIR} src; git clone --recursive ${PX4_FIRMWARE} ../Firmware; colcon build --event-handlers console_direct+ --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Debug"

script:
  - docker run -it --rm -w ${TRAVIS_BUILD_DIR} --env=CCACHE_DIR="${CCACHE_DIR}" --env=LOCAL_USER_ID="$(id -u)" --volume=${CCACHE_DIR}:${CCACHE_DIR}:rw --volume=${TRAVIS_BUILD_DIR}:${TRAVIS_BUILD_DIR}:rw ${DOCKER_CONTAINER} /bin/bash -c "${BUILD}"
