sudo: required

env:
  global:
    - CCACHE_DIR=${HOME}/.ccache
    - PX4_MSGS=https://github.com/PX4/px4_msgs.git
    - CATKIN_BUILD="unset ROS_DISTRO; mkdir -p ~/catkin_ws/src; cd ~/catkin_ws; ln -s ${TRAVIS_BUILD_DIR} src/px4_ros_com; git clone ${PX4_MSGS} -b ros1; cd src/px4_ros_com/scripts; ./build_ros1_workspace.bash"

matrix:
  include:
    - name: Build on ROS Kinetic
      os: linux
      language: cpp
      services:
        - docker
      cache:
      ccache: true
      env:
        - ROS1_DISTRO=kinetic
        - ROS1_ENV=/opt/ros/${ROS1_DISTRO}/setup.bash
        - DOCKER_CONTAINER=px4io/px4-dev-ros2-bouncy:2019-06-27
    - name: Build on ROS Melodic
      os: linux
      language: cpp
      services:
        - docker
      cache:
      ccache: true
      env:
        - ROS1_DISTRO=melodic
        - ROS1_ENV=/opt/ros/${ROS1_DISTRO}/setup.bash
        - DOCKER_CONTAINER=px4io/px4-dev-ros2-crystal:2019-06-27

script:
  # CI runs over all branches containing 'ros1' on the name or that do not contain 'master' in the name
  - if [[ $TRAVIS_BRANCH =~ "ros1" ]] || [[ ! "$TRAVIS_BRANCH" =~ "master" ]]; then docker run -it --rm -w ${TRAVIS_BUILD_DIR} --env=CCACHE_DIR="${CCACHE_DIR}" --env=LOCAL_USER_ID="$(id -u)" --volume=${CCACHE_DIR}:${CCACHE_DIR}:rw --volume=${TRAVIS_BUILD_DIR}:${TRAVIS_BUILD_DIR}:rw ${DOCKER_CONTAINER} /bin/bash -c "source ${ROS1_ENV}; ${CATKIN_BUILD}"; fi
